---
##################################
# ansible configuration
##################################
ansible_user: bradmin

##################################
# Cluster configuration
##################################
cluster_domain: bright-room.net
br_gateway1:
  hostname: br-gateway1
  server_domain: "gateway1.{{ cluster_domain }}"
  dns_domain: "dns.{{ cluster_domain }}"
  ntp_domain: "ntp.{{ cluster_domain }}"
  ip: 172.22.10.1
  mac: e4:5f:01:65:14:70
  external_network_interface: wlan0
  cluster_network_interface: eth0
br_node1:
  hostname: br-node1
  server_domain: "node1.{{ cluster_domain }}"
  ip: 172.22.10.60
  mac: e4:5f:01:65:14:70
  cluster_network_interface: eth0
br_node2:
  hostname: br-node2
  server_domain: "node2.{{ cluster_domain }}"
  ip: 172.22.10.61
  mac: d8:3a:dd:75:fa:14
  cluster_network_interface: eth0
br_node3:
  hostname: br-node3
  server_domain: "node3.{{ cluster_domain }}"
  ip: 172.22.10.62
  mac: d8:3a:dd:75:f8:b5
  cluster_network_interface: eth0
br_node4:
  hostname: br-node4
  server_domain: "node4.{{ cluster_domain }}"
  ip: 172.22.10.70
  mac: d8:3a:dd:43:97:c1
  cluster_network_interface: eth0
br_node5:
  hostname: br-node5
  server_domain: "node5.{{ cluster_domain }}"
  ip: 172.22.10.71
  mac: d8:3a:dd:43:8b:be
  cluster_network_interface: eth0
br_node6:
  hostname: br-node6
  server_domain: "node6.{{ cluster_domain }}"
  ip: 172.22.10.72
  mac: d8:3a:dd:27:29:4a
  cluster_network_interface: eth0
br_external1:
  hostname: br-external1
  server_domain: "external1.{{ cluster_domain }}"
  objects_domain: "objects.{{ cluster_domain }}"
  ip: 172.22.10.80
  mac: dc:a6:32:94:5f:d6
  cluster_network_interface: eth0

timezone: "Asia/Tokyo"

##################################
# External dataSource configuration
##################################
datasource:
  dns:
    - "8.8.8.8"
    - "8.8.4.4"
