---
- name: Enable IPv4 forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Configure iptables-persistent debconf settings
  debconf:
    name: iptables-persistent
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: boolean
  with_items:
    - question: "iptables-persistent/autosave_v4"
      value: "true"
    - question: "iptables-persistent/autosave_v6"
      value: "true"

- name: Install requirement packages
  apt:
    name: "{{ install_packages }}"
    state: present
