---
- name: Remove snap packages tasks
  include_tasks: remove_snap_packages.yaml

- name: default package management
  include_tasks: requirement_package.yaml

- name: RaspberryPi system configuration
  include_tasks: system_configure.yaml

- name: Blacklist storage devices in multipath configuration
  include_tasks: multipath_blacklist.yaml

- name: SSH configuration
  include_tasks: sshd_configure.yaml

