---
- name: Check that the multipath.conf exists
  stat:
    path: "/etc/multipath.conf"
  register: multipath_file_exist

- name: Create multipath.conf file
  template:
    src: multipath.conf.j2
    dest: /etc/multipath.conf
    owner: "root"
    group: "root"
    mode: "0644"
    backup: true
  when: multipath_file_exist.stat.exists
  notify: restart multipath
