---
- name: Ensure SSH daemon is running.
  service:
    name: ssh
    state: started

- name: Update SSH configuration to be more secure.
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    mode: "0644"
    state: present
    validate: "sshd -T -f %s"
  with_items:
    - regexp: "^#?PasswordAuthentication.*"
      line: "PasswordAuthentication no"
    - regexp: "^#?PermitRootLogin.*"
      line: "PermitRootLogin no"
    - regexp: "^#?Port.*"
      line: "Port 22"
    - regexp: "^#?UseDNS.*"
      line: "UseDNS no"
    - regexp: "^#?PermitEmptyPasswords.*"
      line: "PermitEmptyPasswords no"
    - regexp: "^#?ChallengeResponseAuthentication.*"
      line: "ChallengeResponseAuthentication no"
    - regexp: "^#?GSSAPIAuthentication.*"
      line: "GSSAPIAuthentication no"
    - regexp: "^#?X11Forwarding.*"
      line: "X11Forwarding no"
  notify: restart ssh
