services:
  op-connect-api:
    image: 1password/connect-api:latest
    hostname: op-connect-api
    environment:
      OP_SESSION: ${OP_PROD_SESSION}
  op-connect-sync:
    image: 1password/connect-sync:latest
    hostname: op-connect-sync
    environment:
      OP_SESSION: ${OP_PROD_SESSION}
