---
- name: Create temporary directory for Helm
  file:
    path: /tmp/helm-install
    state: directory
    mode: '0755'

- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/helm-install/get_helm.sh
    mode: '0700'

- name: Install Helm
  command: /tmp/helm-install/get_helm.sh
  register: helm_install
  changed_when: "'already exists' not in helm_install.stderr"

- name: Clean up Helm installation files
  file:
    path: /tmp/helm-install
    state: absent
