---
- name: Copy modules-load.d/k8s.conf file
  copy:
    dest: /etc/modules-load.d/k8s.conf
    src: files/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: 0644

- name: Copy sysctl.d/k8s.conf file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    src: files/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644
