---
- name: Create CoreDNS config directory
  file:
    path: "/etc/coredns"
    state: directory
    mode: '0644'

- name: Create CoreDNS configuration
  template:
    src: Corefile.j2
    dest: "/etc/coredns/Corefile"
    mode: "0644"

- name: Create CoreDNS systemd service file
  template:
    src: coredns.service.j2
    dest: /etc/systemd/system/coredns.service
    mode: "0644"

- name: Create etcd data directory
  file:
    path: "/var/lib/etcd"
    state: directory
    mode: '0644'

- name: Create etcd systemd service file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: "0644"

- name: Disable and Stop systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start etcd
  systemd:
    name: etcd
    state: started
    enabled: yes

- name: Enable and start CoreDNS
  systemd:
    name: coredns
    state: started
    enabled: yes
