---
- name: Ensure isc-dhcp-server is running and enabled as configured.
  systemd:
    name: isc-dhcp-server
    state: started
    enabled: true

- name: Configure isc-dhcp-server
  replace: >-
    dest="/etc/default/isc-dhcp-server"
    regexp="{{ item.regexp }}"
    replace="{{ item.replace }}"
  with_items:
    - regexp: "^#DHCPDv4_CONF=/etc/dhcp/dhcpd.conf"
      replace: "DHCPDv4_CONF=/etc/dhcp/dhcpd.conf"
    - regexp: '^INTERFACESv4=""'
      replace: 'INTERFACESv4="{{ br_gateway1.cluster_network_interface }}"'

- name: Configure /etc/dhcp/dhcp.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    mode: 0644
  notify: restart isc-dhcp-server
