---
- name: Set etcd base variables
  set_fact:
    etcd_version: "v3.5.16"
    os_arch: "arm64"

- name: Download etcd archive
  get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-{{ os_arch }}.tar.gz"
    dest: "{{ tmp_dir }}/etcd-{{ etcd_version }}-linux-{{ os_arch }}.tar.gz"
    mode: "0644"

- name: "Extract etcd to {{ tmp_dir }}"
  unarchive:
    src: "{{ tmp_dir }}/etcd-{{ etcd_version }}-linux-{{ os_arch }}.tar.gz"
    dest: "{{ tmp_dir }}"
    remote_src: yes

- name: "Copy etcd binary to {{ install_dir }}"
  copy:
    src: "{{ item.source }}"
    dest: "{{ item.target }}"
    mode: "0755"
    remote_src: yes
  with_items:
    - source: "{{ tmp_dir }}/etcd-{{ etcd_version }}-linux-{{ os_arch }}/etcd"
      target: "{{ install_dir }}/etcd"
    - source: "{{ tmp_dir }}/etcd-{{ etcd_version }}-linux-{{ os_arch }}/etcdctl"
      target: "{{ install_dir }}/etcdctl"
    - source: "{{ tmp_dir }}/etcd-{{ etcd_version }}-linux-{{ os_arch }}/etcdutl"
      target: "{{ install_dir }}/etcdutl"
