---
- name: Enable IPv4 forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Execute install requirement package tasks
  include_tasks: requirement_package.yaml

- name: Execute configure dhcp tasks
  include_tasks: configure_dhcp.yaml

- name: Execute configure dns tasks
  include_tasks: configure_dns.yaml

- name: Execute configure ntp tasks
  include_tasks: configure_ntp.yaml
