---
- name: Configure iptables-persistent debconf settings
  debconf:
    name: iptables-persistent
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: boolean
  loop:
    - { question: 'iptables-persistent/autosave_v4', value: 'true' }
    - { question: 'iptables-persistent/autosave_v6', value: 'true' }

- name: Remove packages
  apt:
    name: "needrestart"
    state: absent

- name: Install requirement packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "dnsutils"
      - "netfilter-persistent"
      - "iptables-persistent"
      - "lsof"
      - "net-tools"
      - "jq"
      - "isc-dhcp-server"
      - "chrony"
      - "wget"
      - "tar"

- name: Install etcd
  include_tasks: install_etcd.yaml

- name: Install coredns
  include_tasks: install_coredns.yaml
