---
- name: Configure iptables-persistent debconf settings
  debconf:
    name: iptables-persistent
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: boolean
  loop:
    - { question: 'iptables-persistent/autosave_v4', value: 'true' }
    - { question: 'iptables-persistent/autosave_v6', value: 'true' }

- name: Remove packages
  apt:
    name: "needrestart"
    state: absent

- name: Register Docker repository
  include_tasks: docker-repository-register.yaml

- name: Install requirement packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "git"
      - "dnsutils"
      - "curl"
      - "ca-certificates"
      - "gnupg"
      - "netfilter-persistent"
      - "iptables-persistent"
      - "nftables"
      - "lsof"
      - "net-tools"
      - "jq"
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
      - "docker-buildx-plugin"
      - "docker-compose-plugin"
