---
- name: Create ntp configuration file
  template:
    src: "chrony.conf.j2"
    dest: "/etc/chrony/chrony.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: true
  notify: restart ntp
