---
- name: Check that the multipath.conf exists
  stat:
    path: /etc/multipath.conf
  register: multipath_file_exist

- name: Append blacklisted multipath.conf file
  blockinfile:
    path: /etc/multipath.conf
    marker: "# {mark} Append by ansible"
    block: "{{ lookup('file', './files/multipath.conf') }}"
    owner: root
    group: root
    mode: 0644
    state: present
  when: multipath_file_exist.stat.exists
  notify: restart multipath
