---
- name: Append hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} Append by ansible"
    block: "127.0.1.1 {{ hostname }}"
    owner: root
    group: root
    mode: 0644
    state: present

- name: Remove symlink resolv.conf
  file:
    path: "path=/etc/resolv.conf"
    state: absent

- name: Create resolv.conf file
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"
    backup: true

- name: Change default GPU Memory Split
  blockinfile:
    path: /boot/firmware/config.txt
    marker: "# {mark} Append by ansible"
    block: "gpu_mem=16"
    owner: root
    group: root
    mode: 0755
    state: present

- name: Change NTP server
  replace: >-
    dest="/etc/systemd/timesyncd.conf"
    regexp="#NTP="
    replace="NTP={{ br_gateway1.ntp_domain }}"

- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: "{{ timezone }}"
  notify: reboot
