---
all:
  children:
    br-cluster:
      hosts:
        br-gateway1:
        br-external1:
        br-node[1:6]:
    gateway:
      hosts:
        br-gateway1:
    clusters:
      children:
        master:
          children:
            primary:
              hosts:
                br-node1:
            secondary:
              hosts:
                br-node[2:3]:
        worker:
          hosts:
            br-node[4:6]:
    external:
      hosts:
        br-external1:
