---
- name: Configure master nodes
  hosts: master
  tags: [ "master" ]
  gather_facts: true
  become: true

  collections:
    - onepassword.connect

  vars:
    op_connect_token:

  environment:
    OP_CONNECT_TOKEN: "{{ lookup('env', 'OP_CONNECT_TOKEN') }}"
    OP_CONNECT_HOST: "{{ lookup('env', 'OP_CONNECT_HOST') }}"

  pre_tasks:
    - name: package update
      include_tasks: tasks/update.yaml
      tags: [ "always" ]

  roles:
    - name: Setup system configuration role
      role: system_setup
      tags: [ "system" ]

    - name: Setup node pre configuration role
      role: node/pre_configuration
      tags: [ "system" ]

    - name: Setup k3s cluster
      role: node/master_setup
      tags: [ "k3s" ]

- name: Configure worker nodes
  hosts: worker
  tags: [ "worker" ]
  gather_facts: true
  become: true

  collections:
    - onepassword.connect

  vars:
    op_connect_token:

  environment:
    OP_CONNECT_TOKEN: "{{ lookup('env', 'OP_CONNECT_TOKEN') }}"
    OP_CONNECT_HOST: "{{ lookup('env', 'OP_CONNECT_HOST') }}"

  pre_tasks:
    - name: package update
      include_tasks: tasks/update.yaml
      tags: [ "always" ]

    - name: Setup Initialize disk
      include_tasks: tasks/init_disk.yaml
      tags: [ "system" ]

  roles:
    - name: Setup system configuration role
      role: system_setup
      tags: [ "system" ]

    - name: Setup node pre configuration role
      role: node/pre_configuration
      tags: [ "system" ]

    - name: Setup k3s cluster
      role: node/worker_setup
      tags: [ "k3s" ]

- name: Labeled worker nodes
  hosts: master
  tags: [ "insert_label" ]
  gather_facts: true

  tasks:
    - name: Label k3s worker nodes
      command:
        cmd: "kubectl label nodes {{ item }} kubernetes.io/role=worker"
      with_items: "{{ groups['worker'] }}"
      run_once: true

- name: Get k3s config file
  hosts: master
  tags: [ "kube_config" ]
  gather_facts: true
  become: true

  tasks:
    - name: Get k3s config file
      run_once: true
      slurp:
        src: "{{ k3s.config_dir }}/k3s.yaml"
      register: kube_config_base64

    - name: Write Kubernetes config file with the correct cluster address
      copy:
        content: "{{ kube_config_base64.content | b64decode | replace('127.0.0.1', br_external1.ip ) }}"
        dest: "/.secret/config"
        mode: "0644"
      delegate_to: localhost
      run_once: true

