---
##################################
# ansible configuration
##################################
hostname: "br-gateway1"
ansible_host: "192.168.2.50"
ansible_ssh_private_key_file: "~/.ssh/br-gateway1"

##################################
# System configuration
##################################
tmp_dir: "/tmp"
install_dir: "/usr/local/bin"

##################################
# DHCP configuration
##################################
dhcp:
  cluster_cidr: 172.22.10.0
  cluster_subnet: 255.255.255.0
  cluster_subnet_cidr: 24
  auto_allocation_ipaddr_range:
    begin: 172.22.10.100
    end: 172.22.10.200
  static_allocation_ipaddr:
    - host: "{{ br_gateway1.hostname }}"
      ip: "{{ br_gateway1.ip }}"
      mac: "{{ br_gateway1.mac }}"
    - host: "{{ br_node1.hostname }}"
      ip: "{{ br_node1.ip }}"
      mac: "{{ br_node1.mac }}"
    - host: "{{ br_node2.hostname }}"
      ip: "{{ br_node2.ip }}"
      mac: "{{ br_node2.mac }}"
    - host: "{{ br_node3.hostname }}"
      ip: "{{ br_node3.ip }}"
      mac: "{{ br_node3.mac }}"
    - host: "{{ br_node4.hostname }}"
      ip: "{{ br_node4.ip }}"
      mac: "{{ br_node4.mac }}"
    - host: "{{ br_node5.hostname }}"
      ip: "{{ br_node5.ip }}"
      mac: "{{ br_node5.mac }}"
    - host: "{{ br_node6.hostname }}"
      ip: "{{ br_node6.ip }}"
      mac: "{{ br_node6.mac }}"
    - host: "{{ br_external1.hostname }}"
      ip: "{{ br_external1.ip }}"
      mac: "{{ br_external1.mac }}"

##################################
# DNS configuration
##################################
dns:
  static_resolve:
    - ip: "{{ br_gateway1.ip }}"
      domains:
        - "{{ br_gateway1.server_domain }}"
        - "{{ br_gateway1.dns_domain }}"
        - "{{ br_gateway1.ntp_domain }}"
    - ip: "{{ br_node1.ip }}"
      domains:
        - "{{ br_node1.server_domain }}"
    - ip: "{{ br_node2.ip }}"
      domains:
        - "{{ br_node2.server_domain }}"
    - ip: "{{ br_node3.ip }}"
      domains:
        - "{{ br_node3.server_domain }}"
    - ip: "{{ br_node4.ip }}"
      domains:
        - "{{ br_node4.server_domain }}"
    - ip: "{{ br_node5.ip }}"
      domains:
        - "{{ br_node5.server_domain }}"
    - ip: "{{ br_node6.ip }}"
      domains:
        - "{{ br_node6.server_domain }}"
    - ip: "{{ br_external1.ip }}"
      domains:
        - "{{ br_external1.server_domain }}"
        - "{{ br_external1.objects_domain }}"
  daynamic_resolve:
    store: "http://{{ br_gateway1.ip }}:2379"

#################################
# ipr-cnrs/nftables　configuration
#################################
nft_old_pkg_list: []

nft_global_default_rules: {}
nft_global_rules:
  005 state management:
    - ct state established,related accept
    - ct state invalid drop

nft_input_default_rules: {}
nft_input_rules:
  000 policy:
    - type filter hook input priority 0; policy drop;
  001 global:
    - jump global
  002 localhost:
    - iif lo accept
  014 icmp:
    - meta l4proto {icmp,icmpv6} accept
  210 input tcp accepted:
    - tcp dport @in_tcp_accept ct state new accept
  211 input udp accepted:
    - udp dport @in_udp_accept ct state new accept

nft_output_default_rules: {}
nft_output_rules:
  000 policy:
    - type filter hook output priority 0;

nft__forward_table_manage: true
nft_forward_default_rules: {}
nft_forward_rules:
  000 policy:
    - type filter hook forward priority 0; policy drop;
  001 global:
    - jump global
  200 lan to wan tcp:
    - iifname $lan_interface ip saddr $lan_network oifname $wan_interface tcp dport @forward_tcp_accept ct state new accept
  210 lan to wan udp:
    - iifname $lan_interface ip saddr $lan_network oifname $wan_interface udp dport @forward_udp_accept ct state new accept
  220 ssh from wan:
    - iifname $wan_interface oifname $lan_interface ip daddr $lan_network tcp dport ssh ct state new accept
  230 http from wan:
    - iifname $wan_interface oifname $lan_interface ip daddr $lan_network tcp dport {http, https} ct state new accept
  240 docker:
    - ct state { established, related } accept;
    - ct state invalid drop;
    - iifname $docker_interface accept;


nft__nat_table_manage: true
nft__nat_default_prerouting_rules: {}
nft__nat_prerouting_rules:
  000 policy:
    - type nat hook prerouting priority 0;

nft__nat_default_postrouting_rules: {}
nft__nat_postrouting_rules:
  000 policy:
    - type nat hook postrouting priority 100;
  005 masquerade lan to wan:
    - ip saddr $lan_network oifname $wan_interface masquerade
    - oifname != $docker_interface masquerade;

nft_define_default: {}
nft_define:
  broadcast and multicast:
    name: badcast_addr
    value: "{ 255.255.255.255, 224.0.0.1, 224.0.0.251 }"
  ip6 broadcast and multicast:
    name: ip6_badcast_addr
    value: "{ ff02::16 }"
  input tcp accepted:
    name: in_tcp_accept
    value: "{ ssh, https, http, iscsi-target, 2379, 6443 }"
  input udp accepted:
    name: in_udp_accept
    value: "{ snmp, domain, ntp, bootps }"
  output tcp accepted:
    name: out_tcp_accept
    value: "{ http, https, ssh }"
  output udp accepted:
    name: out_udp_accept
    value: "{ domain, bootps , ntp }"
  lan interface:
    name: lan_interface
    value: "eth0"
  wan interface:
    name: wan_interface
    value: "wlan0"
  docker interface:
    name: docker_interface
    value: "{ docker0 }"
  lan network:
    name: lan_network
    value: "{{ dhcp.cluster_cidr }}/{{ dhcp.cluster_subnet_cidr }}"
  forward tcp accept:
    name: forward_tcp_accept
    value: "{ http, https, ssh }"
  forward udp accept:
    name: forward_udp_accept
    value: "{ domain, ntp }"

# sets and maps
nft_set_default: {}
nft_set:
  blackhole:
    - type ipv4_addr;
    - elements = $badcast_addr
  ip6blackhole:
    - type ipv6_addr;
    - elements = $ip6_badcast_addr
  in_tcp_accept:
    - type inet_service; flags interval;
    - elements = $in_tcp_accept
  in_udp_accept:
    - type inet_service; flags interval;
    - elements = $in_udp_accept
  out_tcp_accept:
    - type inet_service; flags interval;
    - elements = $out_tcp_accept
  out_udp_accept:
    - type inet_service; flags interval;
    - elements = $out_udp_accept
  forward_tcp_accept:
    - type inet_service; flags interval;
    - elements = $forward_tcp_accept
  forward_udp_accept:
    - type inet_service; flags interval;
    - elements = $forward_udp_accept
