---
- name: Install isc-dhcp-server packages
  apt:
    name: isc-dhcp-server
    state: present

- name: Ensure isc-dhcp-server is running and enabled as configured.
  systemd:
    name: isc-dhcp-server
    state: started
    enabled: true
