---
- name: Download Helm install script
  get_url:
    url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
    dest: "{{ tmp_dir }}/get-helm-3"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Execute Helm install script
  command:
    cmd: "bash {{ tmp_dir }}/get-helm-3"

- name: Remove install script
  file:
    path: "{{ tmp_dir }}/get-helm-3"
    state: absent
