---
- name: Get system architecture
  command:
    cmd: "dpkg --print-architecture"
  register: system_arch
  changed_when: false

- name: Get latest stable Cilium CLI version
  uri:
    url: https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt
    return_content: yes
  register: cilium_version

- name: Set download URL
  set_fact:
    download_url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_version.content | trim }}/cilium-linux-{{ system_arch.stdout }}.tar.gz"

- name: Download Cilium CLI archive and checksum
  get_url:
    url: "{{ item }}"
    dest: "{{ tmp_dir }}/{{ item | basename }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - "{{ download_url }}"
    - "{{ download_url }}.sha256sum"

- name: Verify checksum
  command:
    cmd: "sha256sum --check /tmp/cilium-linux-{{ system_arch.stdout }}.tar.gz.sha256sum"
  args:
    chdir: "{{ tmp_dir }}"
  changed_when: false

- name: Extract Cilium CLI
  unarchive:
    src: "{{ tmp_dir }}/cilium-linux-{{ system_arch.stdout }}.tar.gz"
    dest: "{{ install_dir }}"
    owner: "root"
    group: "root"
    mode: "0755"
    remote_src: yes

- name: Clean up downloaded files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ tmp_dir }}/cilium-linux-{{ system_arch.stdout }}.tar.gz"
    - "{{ tmp_dir }}/cilium-linux-{{ system_arch.stdout }}.tar.gz.sha256sum"
