---
- name: Add br_netfilter
  copy:
    content: "br_netfilter"
    dest: "/etc/modules-load.d/br_netfilter.conf"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Load br_netfilter
  modprobe:
    name: "br_netfilter"
    state: present

- name: Set bridge-nf-call-iptables
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: true
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
