---
- name: Create systemd configs
  template:
    src: "{{ item.systemd_config }}.j2"
    dest: "/etc/systemd/system/{{ item.systemd_config }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - systemd_config: "restic-backup.service"
    - systemd_config: "restic-backup.timer"
    - systemd_config: "restic-clean.service"
    - systemd_config: "restic-clean.timer"
  notify: systemd reload

- name: Enable and start timer
  systemd:
    name: "{{ item.systemd_config }}"
    enabled: true
    state: started
  with_items:
    - systemd_config: "restic-backup.timer"
    - systemd_config: "restic-clean.timer"
